### ISSUE TITLE
PHP 5.4 scheduled to become EOL on PHP.net 14th September

### ISSUE THREAD

**Issue by andytson** [iuscommunity-pkg/php54#4]
According to http://php.net/supported-versions.php, PHP 5.4 will become EOL 14th September.

Before PHP 5.3 was EOL'd, IUS mentioned how you'd handle the php53u packages once this happened (moving the packages to jus-archive).

Due to this happening around 3 months from now, will you be announcing the same for php54?

**Comment by carlgeorge** [comment]
Good call, I send something out to the mailing list soon.
